# Start with CUDA Theano base image
FROM animoid/cuda-theano:latest
MAINTAINER David Jung <david@egomachines.com>
#  based on Dockerfiles by Kai Arulkumaran - https://github.com/Kaixhin/dockerfiles

# Install bleeding-edge Lasagne
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
